name: Build and Publish Binary

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest'

      - name: Install dependencies
        run: bun install --omit dev

      - name: Build executable with Bun
        run: bun build src/index.ts --compile --outfile=dist/obsidian-cli --external:@types/node

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/obsidian-cli
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
